### ISSUE TITLE
Instructors

### ISSUE THREAD

**Issue by Lavasplash** [JustintyC/Custom-Workday-Courselist-Extension#1]
Hi,

Is there any way for the extension to also show the instructors for that section without having to click into the section?

![workday](https://github.com/JustintyC/Custom-Workday-Courselist-Extension/assets/69090408/9b8ee9e8-befd-43e2-ace2-bb0194609f17)

![image](https://github.com/JustintyC/Custom-Workday-Courselist-Extension/assets/69090408/6063c576-a20f-4800-9f8e-e8716f9f26bd)

**Comment by JustintyC** [comment]
that would require me to send an api call to workday for every section loaded, which may cause issues :(

**Comment by Lavasplash** [comment]
ah gotcha, thanks!
